### ISSUE TITLE
Error: Authentication Required

### ISSUE THREAD

**Issue by subhammahanta777** [jarrekk/imgkit#22]
The page I'm trying to create an image for has a Basic authentication mechanism enabled.
Is there a way to provide the basic auth details to imgkit.

Exact Error:

INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:/Users/xavier.r.QUOSPHERE/PycharmProjects/kalpaturu/img2png.py", line 4, in <module>
    imgkit.from_url('http://myurl.com', 'out.png')
  File "C:\Users\xavier.r.QUOSPHERE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\imgkit\api.py", line 21, in from_url
    return rtn.to_img(output_path)
  File "C:\Users\xavier.r.QUOSPHERE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\imgkit\imgkit.py", line 240, in to_img
    raise IOError('wkhtmltoimage reported an error:\n' + stderr)
OSError: wkhtmltoimage reported an error:
Loading page (1/2)
Error: Authentication Required                                    
Rendering (2/2)                                                    
Done                                                               
Exit with code 1 due to network error: AuthenticationRequiredError

**Comment by jarrekk** [comment]
@subhammahanta777 
You can try `--username`/`--password` or `--custom-header`,  for detail please see https://wkhtmltopdf.org/usage/wkhtmltopdf.txt.
