### ISSUE TITLE
Can't pip install imgkit 0.0.8

### ISSUE THREAD

**Issue by dimab0** [jarrekk/imgkit#4]
Missing source_file

**Comment by TimotheeJeannin** [comment]
I do have the same problem. 

```
Collecting imgkit
  Using cached imgkit-0.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-ec80n9cy/imgkit/setup.py", line 25, in long_description
        import pypandoc
    ImportError: No module named 'pypandoc'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ec80n9cy/imgkit/setup.py", line 42, in <module>
        long_description=long_description(),
      File "/tmp/pip-build-ec80n9cy/imgkit/setup.py", line 30, in long_description
        long_desc = open('README.md').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ec80n9cy/imgkit/
```

**Comment by pprmint** [comment]
Encountering the same problem. Any solution you found out? Thanks!

**Comment by v-hunt** [comment]
Hi,
Observed the same issue. Does anyone know any solution?

**Comment by dimab0** [comment]
I was able to instal 0.0.7 instead

~ Dimitry

**Comment by pprmint** [comment]
@dimab0 thanks! I was able to install it as well. Lets just wait for @jarrekk to publish a new version when he merge the fixes. 👍

**Comment by xkortex** [comment]
I ran `pip install pypandoc`, which got rid of that error, but now I'm getting this one: 

```

Collecting imgkit
  Using cached imgkit-0.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mc6k9xe5/imgkit/setup.py", line 42, in <module>
        long_description=long_description(),
      File "/tmp/pip-build-mc6k9xe5/imgkit/setup.py", line 26, in long_description
        long_desc = pypandoc.convert_file('README.md', 'rst')
      File "/home/mike/ve/ml/lib/python3.5/site-packages/pypandoc/__init__.py", line 137, in convert_file
        raise RuntimeError("source_file is not a valid path")
    RuntimeError: source_file is not a valid path
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mc6k9xe5/imgkit/

```

**Comment by jarrekk** [comment]
Thanks all for reporting this bug! 

Since I used Travis CI to release this library at pypi I haven't noticed description I edit before, now `long_description()` is edited to [this](https://github.com/jarrekk/imgkit/blob/master/setup.py#L23-L32) and I install [pandoc](https://github.com/jarrekk/imgkit/blob/master/travis/pandoc.sh) to support readme file at [pypi](https://pypi.python.org/pypi/imgkit/0.0.12), installation will not have error.

Anyway thanks @pprmint and @v-hunt for your PR.
