### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'which'

### ISSUE THREAD

**Issue by JaWas2019** [jarrekk/imgkit#54]
Hey there,

first of all, sorry to be bothering you.
I have a very simple python function which takes an HTML table and converts it to an img:

```
import imgkit

def create_image_from_html(html):
    config = imgkit.config(wkhtmltoimage='/usr/bin/wkhtmltoimage')
    options ={
        "crop-w": "550",
        "xvfb": ""
    }
    imgkit.from_string(html, "portfolio.jpg", options=options, css="table.css", config=config)
    return "portfolio.jpg"
```

It used to run fine, but suddenly it somehow stopped working (Ubuntu Server 20.0.4, Flask with uWSGI). I already uninstalled and installed it from the binary.  I also installed xvbf, just in case.

But I still run into the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./tradingbot/routes.py", line 104, in message
    message = portfolio_message.get_message_payload()
  File "./tradingbot/portfolio_message.py", line 25, in get_message_payload
    *self._get_stocks_block(),
  File "./tradingbot/portfolio_message.py", line 51, in _get_stocks_block
    filepath = create_image_from_html(html)
  File "./tradingbot/image.py", line 5, in create_image_from_html
    config = imgkit.config(wkhtmltoimage='/usr/bin/wkhtmltoimage')
  File "/home/jan/Slackbot/env/lib/python3.8/site-packages/imgkit/api.py", line 101, in config
    return Config(**kwargs)
  File "/home/jan/Slackbot/env/lib/python3.8/site-packages/imgkit/config.py", line 26, in __init__
    self.xvfb = subprocess.Popen(['which', 'xvfb-run'],
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'which'
```

I have confirmed that wkhtmltoimage exists in /usr/bin/, I can see it with ls.
Any idea what could be causing this?

Thank you very much in advance!

**Comment by JaWas2019** [comment]
OK, follow-up: The previous error seems to be caused by the fact that the user used by uWSGI does not have PATH defined. I was able to work around this by changing the Popen which call in imgkit/config.py to an absolute path:

`self.xvfb = subprocess.Popen(['/usr/bin/which', 'xvfb-run'],`

However, this promptly lead to the next error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./tradingbot/routes.py", line 104, in message
    message = portfolio_message.get_message_payload()
  File "./tradingbot/portfolio_message.py", line 25, in get_message_payload
    *self._get_stocks_block(),
  File "./tradingbot/portfolio_message.py", line 51, in _get_stocks_block
    filepath = create_image_from_html(html)
  File "./tradingbot/image.py", line 10, in create_image_from_html
    imgkit.from_string(html, "portfolio.jpg", options=options, css="table.css", config=config)
  File "/home/jan/Slackbot/env/lib/python3.8/site-packages/imgkit/api.py", line 90, in from_string
    return rtn.to_img(output_path)
  File "/home/jan/Slackbot/env/lib/python3.8/site-packages/imgkit/imgkit.py", line 212, in to_img
    result = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: b''
```

I was unable to find a proper way of solving this, as I was not able to figure out where the b"" call comes from (it's a bit hard to trace because this Popen call is executed with passed in args). However, a quick and dirty workaround:

By going to line 212 in imgkit.py and adding a `Shell=True` to the call, I was able to get rid of the error and my bot is now able to properly export images again. I am aware that Shell=True adds unnecessary overhead to the Popen call, but I am not versed enough in Linux to find a better way. Hope this helps anyone who might be struggling with the same thing.

**Comment by jarrekk** [comment]
@JaWas2019 please check out new version and see if this fix your problem: https://github.com/jarrekk/imgkit/blob/V1.1.0/imgkit/config.py
