### ISSUE TITLE
Unable to install in python3 virtualenv

### ISSUE THREAD

**Issue by arayate** [jarrekk/imgkit#9]
Does this library have python3 support?

```
$ pip install imgkit
Collecting imgkit
  Downloading imgkit-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vop6vgef/imgkit/setup.py", line 29
        print e
              ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vop6vgef/imgkit/
```

**Comment by shubhampatel812** [comment]
Same Issue but on windows environment.

**Comment by jarrekk** [comment]
@arayate @shubhampatel812  bug was fixed now, thanks!🙂
